// Generates the two language entry pages from one template:
//   web/index.html     English, served at https://graduate.mangroveintel.com/
//   web/bn/index.html  Bangla,  served at https://graduate.mangroveintel.com/bn/
// The welcome screen is prerendered with the same welcomeMarkup() the browser uses,
// so search engines see the interface text before any script runs.
//
//   node scripts/prerender-pages.mjs          write both pages
//   node scripts/prerender-pages.mjs --check  exit 1 if either page is out of date
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { welcomeMarkup } from '../web/welcome-markup.js';

export const SITE_ORIGIN = 'https://graduate.mangroveintel.com';
export const PAGE_URL = { en: `${SITE_ORIGIN}/`, bn: `${SITE_ORIGIN}/bn/` };
export const PAGE_FILE = { en: 'web/index.html', bn: 'web/bn/index.html' };
export const OG_IMAGE = `${SITE_ORIGIN}/assets/og-image.png`;
const ICON_512 = `${SITE_ORIGIN}/assets/mangrove-graduate-navigator-icon-512.png`;

const META = {
  en: {
    title: 'Mangrove Graduate Navigator | Career Direction for Bangladesh Graduates',
    description: 'Practical career direction for graduates in Bangladesh, based on capabilities, work preferences and real constraints. Available in English and Bangla.',
    ogTitle: 'Mangrove Graduate Navigator',
    ogDescription: 'Practical career direction for graduates in Bangladesh, based on capabilities, work preferences and real constraints.',
    imageAlt: 'Mangrove Graduate Navigator: career direction for graduates in Bangladesh',
    locale: 'en_US',
    homeLabel: 'Mangrove Graduate Navigator home',
    step: 'Step 1 of 4',
    time: 'Usually 10–15 minutes',
    progressLabel: 'Assessment progress',
    languageLabel: 'Language',
  },
  bn: {
    title: 'Mangrove Graduate Navigator | বাংলাদেশের গ্র্যাজুয়েটদের ক্যারিয়ার দিকনির্দেশ',
    description: 'বাংলাদেশের গ্র্যাজুয়েটদের জন্য বাস্তবসম্মত ক্যারিয়ার দিকনির্দেশ—আপনার সক্ষমতা, কাজের পছন্দ এবং বাস্তব সীমাবদ্ধতার ভিত্তিতে। বাংলা ও ইংরেজিতে পাওয়া যায়।',
    ogTitle: 'Mangrove Graduate Navigator',
    ogDescription: 'বাংলাদেশের গ্র্যাজুয়েটদের জন্য বাস্তবসম্মত ক্যারিয়ার দিকনির্দেশ—আপনার সক্ষমতা, কাজের পছন্দ এবং বাস্তব সীমাবদ্ধতার ভিত্তিতে।',
    imageAlt: 'Mangrove Graduate Navigator: বাংলাদেশের গ্র্যাজুয়েটদের জন্য ক্যারিয়ার দিকনির্দেশ',
    locale: 'bn_BD',
    homeLabel: 'Mangrove Graduate Navigator হোম',
    step: 'ধাপ ১ / ৪',
    time: 'সাধারণত ১০–১৫ মিনিট',
    progressLabel: 'মূল্যায়নের অগ্রগতি',
    languageLabel: 'ভাষা',
  },
};

const attr = (value) => String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

function languageLink(target, current) {
  const href = target === 'en' ? '/' : '/bn/';
  const label = target === 'en' ? 'English' : 'বাংলা';
  const active = target === current ? ' class="active" aria-current="page"' : '';
  return `<a href="${href}" hreflang="${target}" lang="${target}"${active} data-language="${target}">${label}</a>`;
}

function structuredData(lang) {
  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Mangrove Graduate Navigator',
    url: PAGE_URL.en,
    description: META.en.ogDescription,
    inLanguage: ['en', 'bn'],
    publisher: {
      '@type': 'Organization',
      name: 'Mangrove Intelligence',
      url: 'https://www.mangroveintel.com/',
      logo: { '@type': 'ImageObject', url: ICON_512, width: 512, height: 512 },
    },
  }, null, 2).replace(/\n/g, '\n  ');
}

export function renderPage(lang) {
  const m = META[lang];
  const other = lang === 'en' ? 'bn' : 'en';
  return `<!doctype html>
<!-- Generated by scripts/prerender-pages.mjs. Edit that script or web/welcome-markup.js, then run: npm run prerender -->
<html lang="${lang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${m.title}</title>
  <meta name="description" content="${attr(m.description)}" />
  <meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" />
  <meta name="googlebot" content="index,follow" />
  <meta name="bingbot" content="index,follow" />
  <meta name="theme-color" content="#064c3a" />

  <link rel="canonical" href="${PAGE_URL[lang]}" />
  <link rel="alternate" hreflang="en" href="${PAGE_URL.en}" />
  <link rel="alternate" hreflang="bn" href="${PAGE_URL.bn}" />
  <link rel="alternate" hreflang="x-default" href="${PAGE_URL.en}" />
  <link rel="icon" href="/assets/favicon-64.png" type="image/png" sizes="64x64" />
  <link rel="icon" href="/assets/mangrove-graduate-navigator-icon.svg" type="image/svg+xml" sizes="any" />
  <link rel="apple-touch-icon" href="/assets/mangrove-graduate-navigator-icon-180.png" sizes="180x180" />
  <link rel="manifest" href="/site.webmanifest" />

  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Mangrove Graduate Navigator" />
  <meta property="og:title" content="${attr(m.ogTitle)}" />
  <meta property="og:description" content="${attr(m.ogDescription)}" />
  <meta property="og:url" content="${PAGE_URL[lang]}" />
  <meta property="og:locale" content="${m.locale}" />
  <meta property="og:locale:alternate" content="${META[other].locale}" />
  <meta property="og:image" content="${OG_IMAGE}" />
  <meta property="og:image:type" content="image/png" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content="${attr(m.imageAlt)}" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${attr(m.ogTitle)}" />
  <meta name="twitter:description" content="${attr(m.ogDescription)}" />
  <meta name="twitter:image" content="${OG_IMAGE}" />

  <script type="application/ld+json">
  ${structuredData(lang)}
  </script>

  <link rel="stylesheet" href="/styles.css" />
  <link rel="stylesheet" href="/refinement-v3.css" />
  <link rel="stylesheet" href="/interaction-v5.css" />
  <link rel="stylesheet" href="/audit-v06.css" />
</head>
<body>
  <header class="site-header">
    <a class="brand brand-lockup" href="${lang === 'en' ? '/' : '/bn/'}" aria-label="${attr(m.homeLabel)}">
      <img class="brand-symbol" src="/assets/mangrove-graduate-navigator-icon.svg" alt="" />
      <span class="brand-copy">
        <strong><span class="brand-parent">Mangrove</span><span class="brand-product">Graduate Navigator</span></strong>
        <small id="brand-subtitle">A Mangrove Intelligence product</small>
      </span>
    </a>
    <nav id="language-toggle" class="language-toggle" aria-label="${m.languageLabel}">
      ${languageLink('en', lang)}
      ${languageLink('bn', lang)}
    </nav>
  </header>

  <main class="shell">
    <div id="progress-wrap" class="progress-wrap hidden" aria-live="polite">
      <div class="progress-meta">
        <span id="progress-label">${m.step}</span>
        <span id="progress-time">${m.time}</span>
      </div>
      <progress id="progress-bar" class="progress-bar" max="100" value="0" aria-label="${m.progressLabel}"></progress>
    </div>
    <section id="app" class="card" aria-live="polite">${welcomeMarkup(lang)}
    </section>
  </main>

  <footer class="site-footer">
    <span><strong>Mangrove Graduate Navigator</strong> · A Mangrove Intelligence product</span>
    <span><a id="footer-privacy" href="/privacy.html" target="_blank" rel="noopener">Terms & Privacy</a></span>
  </footer>

  <script type="module" src="/app.js"></script>
  <script type="module" src="/captcha-start.js"></script>
</body>
</html>
`;
}

async function main() {
  const check = process.argv.includes('--check');
  let stale = false;
  for (const lang of ['en', 'bn']) {
    const file = PAGE_FILE[lang];
    const html = renderPage(lang);
    if (check) {
      const current = (await readFile(file, 'utf8').catch(() => '')).replace(/\r\n/g, '\n');
      if (current !== html) {
        stale = true;
        console.error(`${file} is out of date; run npm run prerender`);
      }
    } else {
      await mkdir(dirname(file), { recursive: true });
      await writeFile(file, html);
      console.log(`Prerendered ${file}`);
    }
  }
  if (stale) process.exit(1);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
