export const copy = {
  en: {
    startEyebrow: 'Career direction, based on evidence',
    startTitle: 'What kind of work can you realistically move toward?',
    startLede: 'A short assessment of what you can do, how you prefer to work, and what is practical for you now. You will get a useful free result before deciding whether you want the full report.',
    start: 'Start assessment',
    sample: 'See a sample full report',
    privacy: 'No CV required',
    privacy3: 'Useful free result first',
    profileTitle: 'First, the basics.',
    profileLede: 'Only what we need to avoid recommending work that is irrelevant to your background.',
    next: 'Continue',
    back: 'Back',
    capTitle: 'What can you do in practice?',
    capLede: 'For each capability, choose the description closest to what you can do today. The four responses move from independent performance to limited exposure; the follow-up asks where you have actually demonstrated it.',
    evidenceTitle: 'Where have you actually used this? Select all that apply.',
    prefTitle: 'Which would you prefer?',
    prefLede: 'Choose the option that feels more like you. Use “Depends / no strong preference” only when neither side genuinely stands out.',
    constraintsTitle: 'What is realistic for you right now?',
    previewLoading: 'Building your free result…',
    previewTitle: 'You already have something to work with.',
    paidTitle: 'Want the full career report?',
    paidBody: 'The full report goes beyond the summary: why each direction fits, the evidence worth building, what to focus on first, and a practical 30-day plan based on the same saved answers.',
    coming: 'Payment is not switched on yet. The launch price will be ৳99.',
  },
  bn: {
    startEyebrow: 'প্রমাণভিত্তিক ক্যারিয়ার দিকনির্দেশ',
    startTitle: 'বাস্তবে কোন ধরনের কাজের দিকে আপনি এগোতে পারেন?',
    startLede: 'আপনি এখন কী করতে পারেন, কী ধরনের কাজ আপনার ভালো লাগে, আর বাস্তবে কোন সুযোগগুলো আপনার জন্য সম্ভব—এই তিনটি বিষয় দেখে আমরা কয়েকটি ক্যারিয়ার দিক সাজাব। পূর্ণ রিপোর্ট নেবেন কি না ঠিক করার আগে ফ্রি ফলটি দেখে নিতে পারবেন।',
    start: 'মূল্যায়ন শুরু করুন',
    sample: 'একটি নমুনা পূর্ণ রিপোর্ট দেখুন',
    privacy: 'CV লাগবে না',
    privacy3: 'আগে কার্যকর ফ্রি ফল',
    profileTitle: 'প্রথমে আপনার সম্পর্কে একটু জানি।',
    profileLede: 'শুধু কয়েকটি তথ্য—যাতে আপনার সঙ্গে না মেলা কাজ দেখানো না হয়।',
    next: 'এগিয়ে যান',
    back: 'পেছনে',
    capTitle: 'কাজের জায়গায় আপনি কী করতে পারেন?',
    capLede: 'প্রতিটি বিষয়ে আপনার বর্তমান অবস্থার সঙ্গে সবচেয়ে মেলে এমন উত্তরটি নিন। এরপর কোথায় এটি ব্যবহার করেছেন, সেটিও জানাবেন।',
    evidenceTitle: 'এটি কোথায় ব্যবহার করেছেন? যেগুলো প্রযোজ্য, সব বেছে নিন।',
    prefTitle: 'কোন ধরনের কাজটি আপনার বেশি ভালো লাগে?',
    prefLede: 'যেটি আপনার সঙ্গে বেশি মেলে সেটি বেছে নিন। সত্যিই কোনো দিক স্পষ্ট না হলে “নির্ভর করে / বিশেষ পছন্দ নেই” নিন।',
    constraintsTitle: 'এখন আপনার জন্য কী কী বাস্তবে সম্ভব?',
    previewLoading: 'আপনার ফ্রি ফল তৈরি হচ্ছে…',
    previewTitle: 'আপনার উত্তর থেকে কয়েকটি পরিষ্কার দিক পাওয়া গেছে।',
    paidTitle: 'আরও বিস্তারিত পূর্ণ রিপোর্ট দেখতে চান?',
    paidBody: 'পূর্ণ রিপোর্টে একই ফলকে আরও বিস্তারিতভাবে দেখানো হবে—প্রতিটি পথ কেন মেলে, কোথায় প্রমাণ আরও পরিষ্কার করা দরকার, কী করলে সবচেয়ে কাজে দেবে এবং আগামী ৩০ দিনে কী করতে পারেন।',
    coming: 'পেমেন্ট এখনও চালু হয়নি। উদ্বোধনী মূল্য হবে ৳৯৯।',
  },
};

const opt = (value, en, bn) => ({ value, en, bn });

export const capabilityItems = [
  {
    code: 'numbers_spreadsheets',
    label_en: 'Numbers & spreadsheets', label_bn: 'সংখ্যা ও স্প্রেডশিট',
    question_en: 'Suppose someone gives you a messy Excel or Google Sheet and asks for a usable result. What can you usually do?',
    question_bn: 'ধরুন আপনাকে একটি এলোমেলো Excel বা Google Sheet দিয়ে ব্যবহারযোগ্য ফল চাওয়া হলো। আপনি সাধারণত কী করতে পারেন?',
    example_en: 'Think about cleaning data, formulas, sorting/filtering, pivots, charts and checking whether the result makes sense.',
    example_bn: 'ডেটা পরিষ্কার করা, formula, sort/filter, pivot, chart এবং ফলটি যুক্তিসঙ্গত কি না যাচাই করার কথা ভাবুন।',
    options: [
      opt('strong','I can clean and organise it, use formulas or pivots, produce a clear output, and check the result independently.','আমি ডেটা পরিষ্কার ও গুছিয়ে formula বা pivot ব্যবহার করে পরিষ্কার output তৈরি এবং ফল নিজে যাচাই করতে পারি।'),
      opt('working','I can handle common formulas, sort/filter and basic charts independently; unfamiliar tasks may need some checking.','সাধারণ formula, sort/filter ও basic chart নিজে করতে পারি; অপরিচিত কাজ হলে কিছু যাচাই বা সহায়তা লাগতে পারে।'),
      opt('basic','I can enter data and do simple calculations when the task is clear, but I need guidance for analysis or more complex features.','কাজ পরিষ্কার থাকলে data entry ও সহজ হিসাব করতে পারি, তবে analysis বা বেশি জটিল feature-এ guidance লাগে।'),
      opt('limited','I have little practical spreadsheet experience and usually need substantial help to set up the work.','স্প্রেডশিটে বাস্তব অভিজ্ঞতা কম; কাজটি গুছিয়ে শুরু করতে সাধারণত যথেষ্ট সাহায্য লাগে।'),
    ],
  },
  {
    code: 'research_information',
    label_en: 'Finding & judging information', label_bn: 'তথ্য খোঁজা ও যাচাই',
    question_en: 'If a manager asks, “Find out what is going on and tell me what we should believe,” what can you do?',
    question_bn: 'কোনো ম্যানেজার যদি বলেন, “বিষয়টা খুঁজে দেখুন এবং কোন তথ্য বিশ্বাসযোগ্য তা বলুন,” আপনি কী করতে পারবেন?',
    example_en: 'For example: compare supplier prices, check a company or market claim, compare several news/data sources, or summarise a policy change. This is not limited to academic research.',
    example_bn: 'যেমন supplier price তুলনা, কোনো কোম্পানি বা বাজারের দাবি যাচাই, কয়েকটি সংবাদ/ডেটা উৎস মিলিয়ে দেখা, বা নীতিগত পরিবর্তন সংক্ষেপ করা। এটি শুধু academic research নয়।',
    options: [
      opt('strong','I can find several relevant sources, judge their reliability, reconcile differences and explain what conclusion the evidence supports.','কয়েকটি প্রাসঙ্গিক উৎস খুঁজে তাদের বিশ্বাসযোগ্যতা বিচার, পার্থক্য মিলিয়ে এবং evidence কোন সিদ্ধান্তকে সমর্থন করে তা ব্যাখ্যা করতে পারি।'),
      opt('working','I can find and compare useful sources independently; ambiguous or conflicting evidence may need a second opinion.','উপযোগী উৎস নিজে খুঁজে তুলনা করতে পারি; অস্পষ্ট বা পরস্পরবিরোধী evidence হলে দ্বিতীয় মতামত দরকার হতে পারে।'),
      opt('basic','I can find information when the question is clear, but I do not always know which source is more reliable or what to do when sources disagree.','প্রশ্ন পরিষ্কার হলে তথ্য খুঁজে পাই, কিন্তু কোন উৎস বেশি নির্ভরযোগ্য বা উৎসে অমিল হলে কী করব—তা সবসময় বুঝি না।'),
      opt('limited','I have limited experience checking sources and often rely on the first useful-looking result or on someone else to verify it.','উৎস যাচাইয়ের অভিজ্ঞতা সীমিত; অনেক সময় প্রথমে ভালো মনে হওয়া ফলের ওপর ভরসা করি বা অন্য কাউকে দিয়ে যাচাই করাই।'),
    ],
  },
  {
    code: 'clear_writing',
    label_en: 'Professional writing', label_bn: 'পেশাগত লেখা',
    question_en: 'How well can you turn information into a clear email, note or short report for work?',
    question_bn: 'তথ্যকে পরিষ্কার professional email, note বা short report-এ কতটা ভালোভাবে রূপ দিতে পারেন?',
    example_en: 'Using AI is fine. The question is whether you can structure, edit, fact-check and take responsibility for the final version.',
    example_bn: 'AI ব্যবহার করা সমস্যা নয়। আসল প্রশ্ন হলো final version গুছানো, edit করা, তথ্য যাচাই করা এবং তার দায়িত্ব নেওয়া আপনি কতটা পারেন।',
    options: [
      opt('strong','I can structure the message for the reader, choose the right tone, edit for brevity and check facts before sending.','পাঠকের প্রয়োজন অনুযায়ী লেখা গুছাতে, সঠিক tone নিতে, সংক্ষিপ্ত করতে এবং পাঠানোর আগে তথ্য যাচাই করতে পারি।'),
      opt('working','My draft is usually clear and usable; I sometimes need editing for structure, tone or brevity.','আমার draft সাধারণত পরিষ্কার ও ব্যবহারযোগ্য; structure, tone বা সংক্ষিপ্ততার জন্য মাঝে মাঝে edit দরকার হয়।'),
      opt('basic','I can get the main point across when the format is clear, but the writing may still need editing to be shorter, more professional or more consistent.','format পরিষ্কার থাকলে মূল কথা লিখতে পারি, তবে লেখা অনেক সময় বেশি দীর্ঘ, informal বা অসমান হয়।'),
      opt('limited','I have limited experience producing professional writing and need substantial help to turn a draft into a work-ready version.','professional writing-এর অভিজ্ঞতা সীমিত; draft-কে work-ready version করতে যথেষ্ট সাহায্য লাগে।'),
    ],
  },
  {
    code: 'explain_present',
    label_en: 'Speaking & presenting', label_bn: 'কথা বলা ও উপস্থাপন',
    question_en: 'When you need to explain something in a meeting or present in front of others, what is closest to you?',
    question_bn: 'মিটিংয়ে কিছু ব্যাখ্যা করা বা অন্যদের সামনে উপস্থাপন করতে হলে কোন বর্ণনাটি আপনার সবচেয়ে কাছাকাছি?',
    example_en: 'Think about organising your points, speaking clearly, handling nerves and answering follow-up questions — not about having a perfect accent.',
    example_bn: 'পয়েন্ট গুছিয়ে বলা, পরিষ্কারভাবে কথা বলা, nervousness সামলানো এবং follow-up প্রশ্নের উত্তর দেওয়ার কথা ভাবুন—perfect accent নয়।',
    options: [
      opt('strong','I can organise my points, present to a group and handle reasonable follow-up questions even if I feel some nerves.','কিছু nervousness থাকলেও পয়েন্ট গুছিয়ে দলের সামনে উপস্থাপন এবং স্বাভাবিক follow-up প্রশ্ন সামলাতে পারি।'),
      opt('working','I explain clearly one-to-one or in a small group; formal presentations are harder, but I can complete them with preparation.','one-to-one বা ছোট দলে পরিষ্কারভাবে বুঝাতে পারি; formal presentation কঠিন লাগে, তবে প্রস্তুতি নিয়ে করতে পারি।'),
      opt('basic','I usually know the material, but under pressure I struggle to organise my words, maintain flow or answer questions confidently.','বিষয়টি সাধারণত জানি, কিন্তু চাপের মধ্যে কথা গুছানো, flow ধরে রাখা বা আত্মবিশ্বাসের সঙ্গে প্রশ্নের উত্তর দিতে সমস্যা হয়।'),
      opt('limited','I have little experience presenting and usually avoid speaking in front of a group when I can.','presentation-এর অভিজ্ঞতা কম এবং সুযোগ থাকলে দলের সামনে কথা বলা এড়িয়ে যাই।'),
    ],
  },
  {
    code: 'customers_persuasion',
    label_en: 'Customers, negotiation & persuasion', label_bn: 'গ্রাহক, দরকষাকষি ও বোঝানো',
    question_en: 'How well can you understand another person’s need and move the conversation toward a useful decision?',
    question_bn: 'অন্য ব্যক্তির প্রয়োজন বুঝে কথোপকথনকে একটি কার্যকর সিদ্ধান্তের দিকে এগিয়ে নিতে আপনি কতটা পারেন?',
    example_en: 'This could be a customer, client, supplier, donor, colleague or partner — not only a sales job.',
    example_bn: 'এটি customer, client, supplier, donor, colleague বা partner—শুধু sales job নয়।',
    options: [
      opt('strong','I can ask useful questions, understand the need, explain trade-offs, respond to objections and make a persuasive case.','উপযোগী প্রশ্ন করে প্রয়োজন বুঝতে, trade-off ব্যাখ্যা করতে, আপত্তির উত্তর দিতে এবং যুক্তি দিয়ে বোঝাতে পারি।'),
      opt('working','I can interact professionally, understand the main need and explain options; negotiation or difficult objections are harder.','পেশাগতভাবে কথা বলতে, মূল প্রয়োজন বুঝতে এবং option ব্যাখ্যা করতে পারি; negotiation বা কঠিন objection সামলানো তুলনামূলক কঠিন।'),
      opt('basic','I can handle straightforward interactions when the purpose is clear, but I am not comfortable influencing or negotiating a decision.','উদ্দেশ্য পরিষ্কার হলে সাধারণ interaction সামলাতে পারি, কিন্তু সিদ্ধান্ত influence বা negotiate করতে স্বাচ্ছন্দ্য কম।'),
      opt('limited','I have little experience with customer-facing or negotiation tasks and generally need support in these situations.','customer-facing বা negotiation ধরনের কাজের অভিজ্ঞতা কম এবং এসব পরিস্থিতিতে সাধারণত support লাগে।'),
    ],
  },
  {
    code: 'organisation',
    label_en: 'Organisation & follow-through', label_bn: 'কাজ গুছানো ও শেষ পর্যন্ত করা',
    question_en: 'When several tasks, deadlines and follow-ups arrive at once, how do you usually manage them?',
    question_bn: 'একসঙ্গে কয়েকটি কাজ, deadline ও follow-up এলে আপনি সাধারণত কীভাবে সামলান?',
    example_en: 'Think about prioritising, keeping track, following up without reminders and finishing reliably.',
    example_bn: 'priority ঠিক করা, track রাখা, reminder ছাড়াই follow-up করা এবং নির্ভরযোগ্যভাবে কাজ শেষ করার কথা ভাবুন।',
    options: [
      opt('strong','I prioritise, keep a reliable system, follow up without reminders and usually finish on time.','priority ঠিক করি, নির্ভরযোগ্যভাবে track রাখি, reminder ছাড়াই follow-up করি এবং সাধারণত সময়মতো কাজ শেষ করি।'),
      opt('working','I keep most work organised and usually meet deadlines; I occasionally miss a follow-up or misjudge priorities.','বেশিরভাগ কাজ গুছিয়ে রাখি এবং সাধারণত deadline মেনে চলি; মাঝে মাঝে follow-up মিস বা priority ভুল হয়।'),
      opt('basic','I complete assigned work when priorities are clear, but I often rely on reminders, lists made by others or deadline pressure.','priority পরিষ্কার থাকলে কাজ শেষ করি, তবে reminder, অন্যের বানানো list বা deadline-এর চাপের ওপর বেশ নির্ভর করি।'),
      opt('limited','I have difficulty keeping track when several tasks compete for attention and need regular reminders or help reprioritising.','একসঙ্গে কয়েকটি কাজ এলে track রাখা কঠিন হয়; নিয়মিত reminder বা priority নতুন করে ঠিক করতে সাহায্য লাগে।'),
    ],
  },
  {
    code: 'teaching_support',
    label_en: 'Teamwork & helping others', label_bn: 'দলগত কাজ ও অন্যকে সহায়তা',
    question_en: 'How well can you work with others, share responsibility and help someone understand or complete a task?',
    question_bn: 'অন্যদের সঙ্গে কাজ, দায়িত্ব ভাগ এবং কাউকে কোনো কাজ বুঝতে বা শেষ করতে সাহায্য করার ক্ষেত্রে আপনি কেমন?',
    example_en: 'Think about classmates, colleagues, club members, clients or junior staff. This is broader than academic teaching.',
    example_bn: 'সহপাঠী, colleague, club member, client বা junior staff-এর কথা ভাবুন। এটি শুধু academic teaching নয়।',
    options: [
      opt('strong','I listen, coordinate responsibilities, explain patiently and adjust when another person or the team is struggling.','মন দিয়ে শুনি, দায়িত্ব সমন্বয় করি, ধৈর্য ধরে বোঝাই এবং অন্যজন বা team সমস্যায় পড়লে পদ্ধতি বদলাই।'),
      opt('working','I cooperate well, communicate reliably and can explain familiar tasks; difficult disagreements may need help.','ভালোভাবে সহযোগিতা করি, নিয়মিত যোগাযোগ রাখি এবং পরিচিত কাজ বোঝাতে পারি; কঠিন মতবিরোধ হলে সাহায্য লাগতে পারে।'),
      opt('basic','I work well when roles are clear, but I am less comfortable coordinating others, guiding someone or resolving disagreement.','দায়িত্ব পরিষ্কার থাকলে ভালো কাজ করি, তবে অন্যকে coordinate করা, guide করা বা মতবিরোধ সামলাতে কম স্বাচ্ছন্দ্য।'),
      opt('limited','I have limited experience with shared responsibility and usually work better when someone else coordinates the team.','shared responsibility-র অভিজ্ঞতা সীমিত; অন্য কেউ team coordinate করলে আমি তুলনামূলক ভালো কাজ করি।'),
    ],
  },
  {
    code: 'digital_content',
    label_en: 'Digital & AI working', label_bn: 'ডিজিটাল ও AI দিয়ে কাজ',
    question_en: 'How well can you use common digital tools — including AI — to get useful work done?',
    question_bn: 'সাধারণ digital tool—AI-সহ—ব্যবহার করে কার্যকর কাজ শেষ করতে আপনি কতটা সক্ষম?',
    example_en: 'Think about documents, slides, online collaboration, search, AI assistants, basic visual tools and checking whether generated output is correct.',
    example_bn: 'document, slide, online collaboration, search, AI assistant, basic visual tool এবং generated output ঠিক কি না যাচাই করার কথা ভাবুন।',
    options: [
      opt('strong','I choose appropriate tools, use AI productively, verify outputs, protect sensitive information and can learn a new tool on my own.','উপযুক্ত tool বেছে নিতে, AI কার্যকরভাবে ব্যবহার ও output যাচাই করতে, sensitive information নিয়ে সতর্ক থাকতে এবং নতুন tool নিজে শিখতে পারি।'),
      opt('working','I am comfortable with common tools and AI and check important output; advanced or unfamiliar features may need guidance.','সাধারণ tool ও AI-তে স্বচ্ছন্দ এবং গুরুত্বপূর্ণ output check করি; advanced বা অপরিচিত feature-এ guidance লাগতে পারে।'),
      opt('basic','I can use familiar apps, templates and basic AI prompts when the task is clear, but I often need step-by-step instructions.','কাজ পরিষ্কার থাকলে পরিচিত app, template ও basic AI prompt ব্যবহার করতে পারি, তবে প্রায়ই step-by-step instruction লাগে।'),
      opt('limited','My practical digital-tool experience is limited and unfamiliar systems slow me down considerably.','বাস্তব digital-tool অভিজ্ঞতা সীমিত এবং অপরিচিত system এলে কাজ অনেক ধীর হয়ে যায়।'),
    ],
  },
  {
    code: 'operational_problem_solving',
    label_en: 'Practical problem-solving', label_bn: 'বাস্তব সমস্যা সমাধান',
    question_en: 'When something goes wrong and there is no obvious instruction, what do you usually do?',
    question_bn: 'কিছু ভুল হলে এবং স্পষ্ট নির্দেশনা না থাকলে আপনি সাধারণত কী করেন?',
    example_en: 'Think about defining the problem, finding the likely cause, comparing options and checking whether the fix worked.',
    example_bn: 'সমস্যা ঠিকভাবে চিহ্নিত করা, সম্ভাব্য কারণ বের করা, option তুলনা এবং সমাধান কাজ করেছে কি না যাচাই করার কথা ভাবুন।',
    options: [
      opt('strong','I define the problem, investigate likely causes, compare options, try a workable solution and check whether it solved the issue.','সমস্যা নির্ধারণ করি, সম্ভাব্য কারণ খুঁজি, option তুলনা করি, ব্যবহারযোগ্য সমাধান চেষ্টা করি এবং সেটি কাজ করেছে কি না যাচাই করি।'),
      opt('working','I solve familiar problems independently; for ambiguous problems I gather information first and then discuss with someone experienced if needed.','পরিচিত সমস্যা নিজে সমাধান করি; অস্পষ্ট সমস্যা হলে আগে তথ্য জোগাড় করি, তারপর দরকার হলে অভিজ্ঞ কারও সঙ্গে আলোচনা করি।'),
      opt('basic','I can deal with the immediate issue when the next step is fairly clear, but I do not always identify the underlying cause or compare alternatives.','পরবর্তী ধাপ মোটামুটি পরিষ্কার হলে তাৎক্ষণিক সমস্যা সামলাই, কিন্তু মূল কারণ বা alternative সবসময় যাচাই করি না।'),
      opt('limited','When instructions are unclear, I usually need someone to diagnose the problem or tell me what to try next.','নির্দেশনা পরিষ্কার না হলে সমস্যা বুঝতে বা পরের ধাপ ঠিক করতে সাধারণত কারও সাহায্য লাগে।'),
    ],
  },
  {
    code: 'fieldwork_data_collection',
    label_en: 'Fieldwork & careful data collection', label_bn: 'ফিল্ডওয়ার্ক ও নির্ভুল তথ্য সংগ্রহ',
    question_en: 'If a job requires you to collect information from people, sites or records, how well could you handle it?',
    question_bn: 'কাজে মানুষ, স্থান বা নথি থেকে তথ্য সংগ্রহ করতে হলে আপনি কতটা ভালোভাবে সামলাতে পারবেন?',
    example_en: 'Think about approaching people, asking consistently, recording accurately, checking missing information and handling refusals or unexpected situations.',
    example_bn: 'মানুষের কাছে যাওয়া, একইভাবে প্রশ্ন করা, নির্ভুলভাবে record করা, missing information যাচাই এবং refusal বা unexpected situation সামলানোর কথা ভাবুন।',
    options: [
      opt('strong','I can follow a protocol, approach people appropriately, record accurately, check missing information and handle common field problems calmly.','protocol মেনে মানুষের কাছে যেতে, নির্ভুলভাবে record করতে, missing information check করতে এবং সাধারণ field problem শান্তভাবে সামলাতে পারি।'),
      opt('working','I can collect information carefully and follow a form or protocol independently; difficult respondents or unusual situations may need support.','form বা protocol মেনে সতর্কভাবে তথ্য নিজে সংগ্রহ করতে পারি; কঠিন respondent বা অস্বাভাবিক পরিস্থিতিতে support লাগতে পারে।'),
      opt('basic','I can follow a clear form or checklist, but I may miss probing, verification or follow-up details without guidance.','পরিষ্কার form বা checklist অনুসরণ করতে পারি, তবে guidance ছাড়া probing, verification বা follow-up detail মিস হতে পারে।'),
      opt('limited','I have little experience collecting information in the field and would need substantial guidance before doing it independently.','field-এ তথ্য সংগ্রহের অভিজ্ঞতা কম; স্বাধীনভাবে করার আগে যথেষ্ট guidance দরকার হবে।'),
    ],
  },
];

export const evidenceOptions = [
  ['university','University coursework / assignment','বিশ্ববিদ্যালয়ের কোর্সওয়ার্ক / অ্যাসাইনমেন্ট'],
  ['personal_volunteer','Personal, volunteer or student activity','নিজস্ব, স্বেচ্ছাসেবী বা শিক্ষার্থী কার্যক্রম'],
  ['internship','Internship / project','ইন্টার্নশিপ / প্রজেক্ট'],
  ['paid_regular','Paid work / freelance work','বেতনভিত্তিক / ফ্রিল্যান্স কাজ'],
];

export const capabilityActionTips = {
  numbers_spreadsheets: { en:'Build one small spreadsheet project using formulas, sorting/filtering and a pivot table; keep the file as evidence.', bn:'formula, sort/filter ও pivot table ব্যবহার করে একটি ছোট spreadsheet প্রজেক্ট বানান এবং evidence হিসেবে fileটি রাখুন।' },
  research_information: { en:'Take one real question, compare at least three sources, and write a one-page conclusion with links to the evidence.', bn:'একটি বাস্তব প্রশ্ন নিয়ে অন্তত তিনটি উৎস তুলনা করুন এবং evidence linkসহ এক পৃষ্ঠার conclusion লিখুন।' },
  clear_writing: { en:'Rewrite one long email or report into a one-page professional version and ask someone to critique clarity and tone.', bn:'একটি দীর্ঘ email বা report-কে এক পৃষ্ঠার professional version-এ লিখুন এবং clarity ও tone নিয়ে feedback নিন।' },
  explain_present: { en:'Record a two-minute explanation of one chart, watch it back, and repeat until the opening and structure feel controlled.', bn:'একটি chart নিয়ে দুই মিনিটের explanation record করুন, দেখে আবার বলুন—opening ও structure নিয়ন্ত্রণে না আসা পর্যন্ত।' },
  customers_persuasion: { en:'Practise a short role-play: ask three questions to understand a need, recommend one option and respond to one objection.', bn:'একটি short role-play করুন: প্রয়োজন বোঝার জন্য তিনটি প্রশ্ন করুন, একটি option recommend করুন এবং একটি objection-এর উত্তর দিন।' },
  organisation: { en:'Use one simple task tracker for two weeks and keep deadlines, next actions and follow-ups in one place.', bn:'দুই সপ্তাহ একটি simple task tracker ব্যবহার করে deadline, next action ও follow-up এক জায়গায় রাখুন।' },
  teaching_support: { en:'Take responsibility for one shared task and practise giving a clear handover or explaining the process to someone else.', bn:'একটি shared task-এর দায়িত্ব নিন এবং clear handover দেওয়া বা অন্য কাউকে process বোঝানোর practice করুন।' },
  digital_content: { en:'Choose one recurring task and use AI or another digital tool to make it faster; verify the output and document the workflow.', bn:'একটি recurring task বেছে AI বা অন্য digital tool দিয়ে দ্রুত করুন; output যাচাই করে workflow লিখে রাখুন।' },
  operational_problem_solving: { en:'For one everyday problem, write the problem, likely cause, three options, the option you chose and what happened.', bn:'একটি দৈনন্দিন সমস্যা নিয়ে problem, সম্ভাব্য cause, তিনটি option, কোনটি নিলেন এবং কী হলো—লিখে রাখুন।' },
  fieldwork_data_collection: { en:'Create a 10-question form, collect five practice responses, then check missing answers, consistency and recording errors.', bn:'১০টি প্রশ্নের form বানিয়ে পাঁচটি practice response নিন, তারপর missing answer, consistency ও recording error যাচাই করুন।' },
};